# Generated by Django 6.0.1 on 2026-01-22 04:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['username'], name='users_user_usernam_65d164_idx'), models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx')],
            },
        ),
    ]
